#! /bin/bash
#
#  U.S. Geological Survey
#
#  File - gridmet
#
#  Purpose - Docker entry-point for Gridmet container.
#
#  Author - Andrew Halper
#

if [ "$NHM_DRY_RUN" = true ]; then
	echo "gridmet service entry-point in dry-run mode:"
	echo
	echo "   USER: $USER"
	exit 0
fi

/opt/conda/bin/python -u onhm-fetcher-parser/pkg/Gridmet_current.py
