#! /bin/bash
#
# U.S. Geological Survey
#
# File - ofp
#
# Purpose - Docker entry-point for NHM ofp container.
#
# Authors - Ivan Suftin, Richard McDonald, Steven Markstrom,
#           Andrew Halper
#
echo "CBHFILLER IDER: $CBH_IDER"

/opt/conda/bin/python \
-u /usr/local/src/onhm-runners/cbh_filler/cbh_filler.py \
/nhm/NHM-PRMS_CONUS_GF_1_1/input \
/nhm/NHM-PRMS_CONUS_GF_1_1/input \
/usr/local/src/onhm-runners/cbh_filler/nhm_id.txt \
/usr/local/src/onhm-runners/cbh_filler/miss_to_pres_mapping.csv \
