#! /bin/bash
#
# U.S. Geological Survey
#
# File - run
#
# Purpose - Simulate NHM run on Shifter, as might be done by Jenkins.
#
# Author - Andrew Halper
#

# if on HPC ...
if uname -r | grep cray > /dev/null 2>&1 ; then
  # run as Slurm batch job at 16:45 PST
  offset=`date +%z | tr -d 0`
  sbatch --parsable --job-name=nhm --begin=`expr 14 + 8 + $offset`:45 run.sl
else
  # run on Docker
  docker-compose build --parallel base_image

  # even though run.sl is a Slurm script, it is also a Bash script, so
  # we take advantage of this by using it to run on both platforms
  bash run.sl
fi
