#! /bin/bash
#
# U.S. Geological Survey
#
# File - run
#
# Purpose - Simulate NHM run on Shifter, as might be done by Jenkins.
#
# Author - Andrew Halper
#

while getopts "nx" opt; do
    case "$opt" in
    n)  begin=now		# begin Slurm job now (if applicable)
        ;;
    x)  shopt -s extdebug	# run scripts in debug mode
	export X=-x
        ;;
    esac
done

# if on HPC ...
if uname -r | grep cray > /dev/null 2>&1 ; then
    if [ "$begin" = now ]; then
	export BEGIN=`date -d 'now +1 minute' +%H:%M`
    else
	# run as Slurm batch job at 6:00 p.m. MST
	export BEGIN=18:00
	export TZ=MST
    fi
    # ... run on Shifter via Slurm
    sbatch --parsable --job-name=nhm --begin=$BEGIN run.sl
else
    # ... run on Docker
    docker-compose build --parallel base_image

    # even though run.sl is a Slurm script, it is also a Bash script, so
    # we take advantage of this by using it to run on both platforms
    bash "$X" run.sl
fi
