#! /bin/bash
#
# U.S. Geological Survey
#
# File - nhm-prms
#
# Purpose - Docker entry-point for nhm-prms container.
#
# Authors - Andrew Halper, Steven Markstrom

. /usr/local/share/nhm/nhm.sh	# use NHM shell functions library

# TODO: this can be factored-out; artifact of translating onhm.py from
# Python to the shell.
run() {
  st="$1"; shift
  et="$1"; shift
  prms_path="$1"; shift
  work_dir="$1"; shift
  init_flag="$1"; shift
  save_flag="$1"; shift
  control_file="$1"; shift
  init_file="$1"; shift
  save_file="$1"; shift
  log_file_name="$1"
  
  start_args=" -set start_time `echo $st | sed 's/-/,/g'`,0,0,0"
  end_args=" -set end_time `echo $et | sed 's/-/,/g'`,0,0,0"
  
  if [ "$init_flag" -ne 0 ]; then
    init_vars_from_file=' -set init_vars_from_file 1'
    var_init_file=" -set var_init_file $init_file"
  else
    init_vars_from_file=' -set init_vars_from_file 0'
    var_init_file=''
  fi

  if [ "$save_flag" -ne 0 ]; then
    save_vars_to_file=' -set save_vars_to_file 1'
    var_save_file=" -set var_save_file $save_file"
  else
    save_vars_to_file = ' -set save_vars_to_file 0'
    var_save_file = ''
  fi
  
  control_arg=" -C $control_file"

  cd $work_dir && \
    $("$prms_path $start_args $end_args $init_vars_from_file \
    		  $var_save_file $var_init_file $save_vars_to_file \
		  $control_arg")

  # TODO: send output to $log_file_name? See onhm.py.
  
} # run

dir='/var/lib/nhm/NHM-PRMS_CONUS/'
restart_dir='restart/'

. /usr/local/share/nhm/nhm.sh	# NHM shell functions library

i=$(restart_interval $dir 'restart/' '59')
start_date=$(interval_start $i)
end_date=$(interval_end $i)

# Remove the verification file before running PRMS.
rm -f "$dirPRMS_VERIFIED_*"

# find last simulation date
# TODO: need to find how this is used in PRMS. See onhm.py.
t=$(last_simulation_date $dir $restart_dir)

# Run PRMS for the prescribed period.
run $start_date $end_date $HOMEDIR/prms/prms/prms $dir 1 0 \
    './NHM-PRMS.control' "$restart_dir$t.restart" '' ''
