#! /bin/bash
#
# U.S. Geological Survey
#
# File - prms
#
# Purpose - Docker/Shifter entry-point for nhm-prms service.
#
# Authors - Andrew Halper, Steven Markstrom
#

# PRMS needs to be run in a directory relative to its data files (in
# subdirectories)
cd /nhm/NHM-PRMS_CONUS_GF_1_1 && $NHM_SOURCE_DIR/prms/prms/prms \
  -set start_time $START_TIME -set end_time $END_TIME \
  -set init_vars_from_file 1 \
  -set var_init_file /nhm/NHM-PRMS_CONUS_GF_1_1/restart/$RESTART_DATE.restart \
  -set save_vars_to_file $SAVE_VARS_TO_FILE \
  -set var_save_file $VAR_SAVE_FILE \
  -C /nhm/NHM-PRMS_CONUS_GF_1_1/NHM-PRMS.control
