#! /bin/bash
#
# U.S. Geological Survey
#
# File - prms
#
# Purpose - Docker entry-point for nhm-prms container.
#
# Authors - Andrew Halper, Steven Markstrom
#

# PRMS needs to be run in a directory relative to its data files (in
# subdirectories)
if [ $PRMS_RUN_TYPE = 0 ]; then
  cd /nhm/NHM-PRMS_CONUS_GF_1_1
else
  cd /nhm/NHM-PRMS_CONUS_GF_1_1/forecast
fi

$NHM_SOURCE_DIR/prms/prms/prms_hpc \
  -set start_time $PRMS_START_TIME -set end_time $PRMS_END_TIME \
  -set init_vars_from_file $PRMS_INIT_VARS_FROM_FILE \
  -set var_init_file $PRMS_VAR_INIT_FILE \
  -set save_vars_to_file $PRMS_SAVE_VARS_TO_FILE \
  -set var_save_file $PRMS_VAR_SAVE_FILE \
  -C $PRMS_CONTROL_FILE
