#! /bin/bash
#
# U.S. Geological Survey
#
# File - gmetl_cfsv2
#
# Purpose - Docker entry-point for NHM gmetl_cfsv2 container.
#
# Authors - Richard McDonald, Andrew Halper
#

/opt/conda/bin/python \
  -u rungmetl_cfs.py \
     -t median -s /nhm/gridmetetl/nhm_hru_data_gfv11/GFv1.1_v2e_geographic.shp \
     -w /nhm/gridmetetl/nhm_hru_data_gfv11/tmp_Gridmet_weights_hru_v1_1e.csv \
     -o $CBH_IDIR \
     -e /nhm/gridmetetl/nhm_hru_data_gfv11/package.gpkg
     

