#! /bin/bash
#
# U.S. Geological Survey
#
# File - gmetl_cfsv2
#
# Purpose - Docker entry-point for NHM gmetl_cfsv2 container.
#
# Authors - Richard McDonald, Andrew Halper
#

/opt/conda/bin/python \
  -u $NHM_SOURCE_DIR/gridmetetl/gridmetetl/gridmet_etl.py \
     -t date -p $START_DATE $END_DATE \
     -i /nhm/gridmetetl/nhm_hru_data_gfv11 \
     -o $CBH_IDIR \
     -w /nhm/gridmetetl/nhm_hru_data_gfv11/tmp_Gridmet_weights_hru_v1_1e.csv \
     --partial=true
