#! /bin/bash
#
# U.S. Geological Survey
#
# File - ofp
#
# Purpose - Docker entry-point for NHM ofp container.
#
# Authors - Ivan Suftin, Richard McDonald, Steven Markstrom,
#           Andrew Halper
#

if [ "$NHM_DRY_RUN" = true ]; then
  echo "ofp service entry-point in dry-run mode:"
  echo
  echo "   NHM_DATA_DIR: $NHM_DATA_DIR"
  echo "   SOURCE_DIR: $SOURCE_DIR"
  echo "   NHM_INTERVAL: $NHM_INTERVAL"
  exit 0
fi

dir=$NHM_DATA_DIR/NHM-PRMS_CONUS/

. /usr/local/share/nhm/nhm.sh	# use NHM shell functions library

# if simulation interval is not specified...
if [ -z "$NHM_INTERVAL" ]; then
    # ...calculate restart interval
    i=$(restart_interval $dir 'restart/' '59')
else
    i=$NHM_INTERVAL
fi

/opt/conda/bin/python -u $SOURCE_DIR/onhm-fetcher-parser/pkg/climate_etl.py \
		      -t date -p `echo $i | sed 's/\// /'` \
		      -i $NHM_DATA_DIR/ofp/nhm_hru_data \
		      -o $dir\input \
		      -w $NHM_DATA_DIR/ofp/nhm_hru_data/weights.csv
