#! /bin/bash
# U.S. Geological Survey
#
# File - ofp
#
# Purpose - Docker entry-point for NHM ofp container.
#
# Authors - Ivan Suftin, Richard McDonald, Steven Markstrom,
#           Andrew Halper
#

dir='/var/lib/nhm/NHM-PRMS_CONUS/'

. /usr/local/share/nhm/nhm.sh	# use NHM shell functions library

# calculate restart interval
i=$(restart_interval $dir 'restart/' '59')

/opt/conda/bin/python -u $SOURCE_DIR/onhm-fetcher-parser/pkg/climate_etl.py \
		      -t date -p `echo $i | sed 's/\// /'` \
		      -i /var/lib/nhm/ofp/nhm_hru_data \
		      -o $dir/input \
		      -w /var/lib/nhm/ofp/nhm_hru_data/weights.csv
