#!/bin/bash

#/opt/conda/bin/python -u onhm-fetcher-parser/pkg/onhm_fp_script.py -d "$NUMDAYS" -i /var/lib/nhm/ofp/Data -o /var/lib/nhm/ofp/Output
/opt/conda/bin/python -u onhm-fetcher-parser/pkg/climate_etl.py -t date -p "$START_DATE" "$END_DATE"  -i /var/lib/nhm/ofp/Data -o /var/lib/nhm/ofp/Output -w var/lib/nhm/ofp/Data/weights.csv
