#! /bin/bash
#
# U.S. Geological Survey
#
# File - ncf2cbh
#
# Purpose - Docker entry-point for ncf2cbh container.
#
# Authors - Richard McDonald, Steven Markstrom,
#           Andrew Halper
#

/opt/conda/bin/python \
    -u $NHM_SOURCE_DIR/onhm-runners/ncf2cbh/ncf2cbh_gfv11.py \
    /nhm/NHM-PRMS_CONUS_GF_1_1/input/ \
    $END_DATE
    