#! /bin/bash
#
#  U.S. Geological Survey
#
#  File - verifier
#
#  Purpose - Docker entry-point for verifier service.
#
#  Author - Andrew Halper
#

if [ "$NHM_DRY_RUN" = true ]; then
	echo "verifier service entry-point in dry-run mode:"
	echo
	echo "   USER: $USER"
	exit 0
fi

/opt/conda/bin/python -u \
		      /usr/local/src/onhm-verify-eval/src/prms_verifier.py \
		      $NHM_DATA_DIR/NHM-PRMS_CONUS/
