#! /bin/bash
#
#  U.S. Geological Survey
#
#  File - data-loader
#
#  Purpose - Docker entry-point for data-loader container.
#
#  Author - Andrew Halper
#

if [ "$NHM_DRY_RUN" = true ]; then
	echo "data_loader service entry-point in dry-run mode:"
	echo
	echo "   NHM_DATA_DIR: $NHM_DATA_DIR"
	echo "   USER: $USER"
	echo "   HRU_DATA_PKG: $HRU_DATA_PKG"
	echo "   HRU_SOURCE: $HRU_SOURCE"
	echo "   PRMS_DATA_PKG: $PRMS_DATA_PKG"
	echo "   PRMS_SOURCE: $PRMS_SOURCE"
	exit 0
fi

set -e

if [ -z "$NHM_DATA_DIR" ]; then
    echo "NHM_DATA_DIR not set"
    exit 1			# we can't proceed
fi

# if the data directory does not exist...
if [ ! -e "$NHM_DATA_DIR" ]; then
  # ...create it, as well as ofp/
  mkdir -p $NHM_DATA_DIR/ofp
  chown -R $USER $NHM_DATA_DIR
  chgrp -R $USER $NHM_DATA_DIR
fi

# if ofp, HRU shapefiles are not present...
if [ ! -e $NHM_DATA_DIR/ofp/nhm_hru_data ]; then
  cd $NHM_DATA_DIR/ofp
  # ...download archive
  wget --waitretry=3 --retry-connrefused "$HRU_SOURCE"
  # uncompress archive
  tar -xvzf "$HRU_DATA_PKG"
  rm -f "$HRU_DATA_PKG"
else
  echo "HRU shapefiles already loaded"
fi

# if PRMS workspace is not present...
if [ ! -e $NHM_DATA_DIR/NHM-PRMS_CONUS ]; then
  cd $NHM_DATA_DIR
  # ...download it
  wget --waitretry=3 --retry-connrefused "$PRMS_SOURCE"
  unzip -o `basename $PRMS_DATA_PKG .zip`
  rm -f "$PRMS_DATA_PKG"
else
  echo "PRMS workspace already loaded"
fi
