#! /bin/bash
#
#  File - nhm
#
#  Purpose - Docker entry-point for data-loader container.
#
#  Author - Andrew Halper
#

set -e

# if ofp, HRU shapefiles are not present...
if [ ! -e /nhm/ofp/nhm_hru_data ]; then
    cd /nhm/ofp
    # ...download archive
    wget --waitretry=3 --retry-connrefused "$HRU_SOURCE"
    # uncompress archive
    tar -xvzf "$HRU_DATA_PKG"
    rm -f "$HRU_DATA_PKG"
else
    echo "HRU shapefiles already loaded"
fi

# if PRMS workspace is not present...
if [ ! -e /nhm/NHM-PRMS_CONUS ]; then
    cd /nhm
    # ...download it
    wget --waitretry=3 --retry-connrefused "$PRMS_SOURCE"
    unzip -o `basename $PRMS_DATA_PKG .zip`
    rm -f "$PRMS_DATA_PKG"
else
    echo "PRMS workspace already loaded"
fi
