#! /bin/bash
#
# U.S. Geological Survey
#
# File - nhm-prms
#
# Purpose - Docker entry-point for nhm-restart container.
#
# Authors - Andrew Halper, Steven Markstrom
#
# DANGER: there is a lot of code copied directly from
#         docker-images/nhmusgs-nhm-prms/nhm-prms

. /usr/local/share/nhm/nhm.sh	# use NHM shell functions library

# TODO: this can be factored-out; artifact of translating onhm.py from
# Python to the shell.
run() {
  st="$1"; shift
  et="$1"; shift
  prms_path="$1"; shift
  work_dir="$1"; shift
  init_flag="$1"; shift
  save_flag="$1"; shift
  control_file="$1"; shift
  init_file="$1"; shift
  save_file="$1"; shift
  log_file_name="$1"
  
  start_args=" -set start_time `echo $st | sed 's/-/,/g'`,0,0,0"
  end_args=" -set end_time `echo $et | sed 's/-/,/g'`,0,0,0"
  
  if [ "$init_flag" -ne 0 ]; then
    init_vars_from_file='-set init_vars_from_file 1'
    var_init_file=" -set var_init_file $init_file"
  else
    init_vars_from_file='-set init_vars_from_file 0'
    var_init_file=''
  fi

  if [ "$save_flag" -ne 0 ]; then
    save_vars_to_file='-set save_vars_to_file 1'
    var_save_file="-set var_save_file $save_file"
  else
    save_vars_to_file='-set save_vars_to_file 0'
    var_save_file=''
  fi
  
  control_arg="-C $control_file"

  cd $work_dir && \
    $prms_path $start_args $end_args $init_vars_from_file \
    		  $var_save_file $var_init_file $save_vars_to_file \
		  $control_arg

  # TODO: send output to $log_file_name? See onhm.py.
  
} # run

dir='/var/lib/nhm/NHM-PRMS_CONUS/'
restart_dir='restart/'

. /usr/local/share/nhm/nhm.sh	# NHM shell functions library

i=$(restart_interval $dir 'restart/' '59')
start_date_restart=$(interval_start $i)

# This code similar to code in nhm.sh.
yesterday=`date --date "$today -1 days" --rfc-3339='date'`
end_date_restart=`date --date "$yesterday -$gridmet_provisional_days days" \
           --rfc-3339='date'`

# find last simulation date used for the init restart file
t=$(last_simulation_date $dir $restart_dir)

# Run PRMS to make the updated restart file
restart_fn = end_date_restart.strftime('%Y-%m-%d') + '.restart'

run $start_date_restart $end_date_restart $HOMEDIR/prms/prms/prms $dir 1 1 \
    './NHM-PRMS.control' "$restart_dir$t.restart" $restart_fn ''
