#! /bin/bash
#
#  U.S. Geological Survey
#
#  File - out2ncf
#
#  Purpose - Docker/Shifter entry-point script for out2ncf service.
#
#  Author - Andrew Halper <ashalper@usgs.gov>
#

/opt/conda/bin/python -u \
   /usr/local/src/onhm-runners/out2ncf/prms_outputs2a_ncf.py \
   /nhm/NHM-PRMS_CONUS_GF_1_1/
